export const SEED_STUDENTS: { rollNumber: string; name: string }[] = [
  { rollNumber: 'BCSF23M001', name: 'AROOJ ABBAS' },
  { rollNumber: 'BCSF23M002', name: 'HAFIZ ABDUL QADIR' },
  { rollNumber: 'BCSF23M003', name: 'AFAQ HUSSAIN' },
  { rollNumber: 'BCSF23M004', name: 'HASSAN AYOUB' },
  { rollNumber: 'BCSF23M005', name: 'MOHAMMAD IBRAHEEM QURESHI' },
  { rollNumber: 'BCSF23M006', name: 'HUDA LIAQAT' },
  { rollNumber: 'BCSF23M007', name: 'MARYYAM TANVEER' },
  { rollNumber: 'BCSF23M008', name: 'MAHAD MUSTAFA' },
  { rollNumber: 'BCSF23M009', name: 'MUHAMMAD TAYYIB' },
  { rollNumber: 'BCSF23M010', name: 'AYESHA WAQAR' },
  { rollNumber: 'BCSF23M012', name: 'MINAHIL SHAHID' },
  { rollNumber: 'BCSF23M013', name: 'HADIA SAQIB' },
  { rollNumber: 'BCSF23M014', name: 'FATIMA' },
  { rollNumber: 'BCSF23M015', name: 'JAVERIA SURRIYA' },
  { rollNumber: 'BCSF23M016', name: 'JAWAIRIA RIAZ' },
  { rollNumber: 'BCSF23M017', name: 'SAMAMA ZAID ABID' },
  { rollNumber: 'BCSF23M018', name: 'HAFIZ MUHAMMAD OWN MUSTAFVI' },
  { rollNumber: 'BCSF23M019', name: 'HAFIZA AYESHA IQBAL' },
  { rollNumber: 'BCSF23M020', name: 'ASAD ULLAH' },
  { rollNumber: 'BCSF23M021', name: 'AZFAR SAGHIR' },
  { rollNumber: 'BCSF23M022', name: 'ABDUL BASIT' },
  { rollNumber: 'BCSF23M023', name: 'SHAHRAM MUNSAF' },
  { rollNumber: 'BCSF23M024', name: 'MUHAMMAD HUZAIFA ALI' },
  { rollNumber: 'BCSF23M025', name: 'MUHAMMAD SUBHAN' },
  { rollNumber: 'BCSF23M026', name: 'SYED ALI AHMAD BUKHARI' },
  { rollNumber: 'BCSF23M027', name: 'MUHAMMAD ZOHAIB' },
  { rollNumber: 'BCSF23M029', name: 'HASSAN ALI PANSOTA' },
  { rollNumber: 'BCSF23M030', name: 'HASNAIN AHMAD' },
  { rollNumber: 'BCSF23M031', name: 'FATIMA MIRZA' },
  { rollNumber: 'BCSF23M032', name: 'ABDUL REHMAN' },
  { rollNumber: 'BCSF23M033', name: 'LAIBA NAVEED' },
  { rollNumber: 'BCSF23M035', name: 'MUHAMMAD MUDASSAR BAIG' },
  { rollNumber: 'BCSF23M036', name: 'MUHAMMAD ABDULLAH SHAFIQ' },
  { rollNumber: 'BCSF23M037', name: 'MUHAMMAD ABUBAKAR' },
  { rollNumber: 'BCSF23M039', name: 'AREEJ FATIMA' },
  { rollNumber: 'BCSF23M040', name: 'MUHAMMAD JAWAD TARIQ' },
  { rollNumber: 'BCSF23M041', name: 'ARIBA KASHIF' },
  { rollNumber: 'BCSF23M042', name: 'HAFIZ SYED SHOAIB AHMAD' },
  { rollNumber: 'BCSF23M043', name: 'MYSHA ZESHAN' },
  { rollNumber: 'BCSF23M046', name: 'Muhammad Wasif' },
  { rollNumber: 'BCSF23M047', name: 'MUAZZAM ALI' },
  { rollNumber: 'BCSF23M048', name: 'ABDULLAH BIN ZUBAIR' },
  { rollNumber: 'BCSF23M049', name: 'AREESHA FATIMA' },
  { rollNumber: 'BCSF23M050', name: 'SYEDA SADAF GILLANI' },
  { rollNumber: 'BCSF23M051', name: 'FATIMA NAVEED' },
  { rollNumber: 'BCSF23M052', name: 'ARSAL RIAZ' },
  { rollNumber: 'BCSF23M055', name: 'QAMAR ABBAS' },
  { rollNumber: 'BCSF23M056', name: 'HAMZA MUSTAFA' },
  { rollNumber: 'BCSF23M057', name: 'MALAK SAIF UR REHMAN' },
  { rollNumber: 'BCSF23M058', name: 'SADIA QASIM' },
  { rollNumber: 'BCSF23M059', name: 'QADIR BUX' },
  { rollNumber: 'BCSF23M060', name: 'SADIA' },
];
